# ===========================================================================
#   KMS App Configuration
# ===========================================================================

# = ----------------------------------------------------------------------- =
# - kms-app identifier
# - ----------------------------------------------------------------------- -
kms.app.id                      = T.PG.API.GPL
# = ----------------------------------------------------------------------- =

# = ----------------------------------------------------------------------- =
# - kms-server ip/port
# - ----------------------------------------------------------------------- -
kms.server.ip                   = 10.0.14.226
kms.server.port                 = 21091
kms.server.so-timeout           = 10000
kms.server.conn-timeout         = 3000
# - ----------------------------------------------------------------------- -
kms.server.lb.mode              = ready
kms.server.lb.ip                = 10.0.14.226
kms.server.lb.port              = 21093
# = ----------------------------------------------------------------------- =

# = ----------------------------------------------------------------------- =
# - LOG \uC124\uC815
# - ----------------------------------------------------------------------- -
kms.log.enable                  = true
kms.log.dir                     = D:\\KCP_Project\\KCP_PROJECT_PANGYO\\API_Project\\Google_Project\\local_log\\kmc
kms.log.file                    = %d_kms_app.log
kms.log.time-format             = %m%d-%H%M%S
kms.log.level                   = 0
# = ----------------------------------------------------------------------- =

# = ----------------------------------------------------------------------- =
# - BTW-Crypto \uC124\uC815
# - ----------------------------------------------------------------------- -
btwcrypto.jar.path=${kms.home}/lib
btwcrypto.status.traced=true
btwcrypto.selftest.traced=false
btwcrypto.selftest.mode=approved-minimal
btwcrypto.approved.mode=false
# = ----------------------------------------------------------------------- =

# = ----------------------------------------------------------------------- =
#  \uC751\uC6A9 key store
# - ----------------------------------------------------------------------- -
kms.app.cert.path=${kms.home}/conf/appCert.der
kms.app.prik.path=${kms.home}/conf/appPri.key
kms.app.prik.passwd=RN+j6bKQn4XSFpLOCoiqdQ==
# = ----------------------------------------------------------------------- =

# = ----------------------------------------------------------------------- =
# - Application Properties \uC124\uC815
# - ----------------------------------------------------------------------- -
kms.app.charset                 = euc.kr
# = ----------------------------------------------------------------------- =

# ===========================================================================
