# maria db 설정
spring:
  datasource:
    url: jdbc:mariadb://서버아이피정보:33906/test?useUnicode=true&characterEncoding=utf8_bin&characterSetResults=utf8_bin
    username: logadm
#    password: eEq6BHJNHGkrlPGzfHZLaw==
    password: logadm913
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 600000
      max-lifetime: 1800000

